version: '3.8'

services:
    backend:
        container_name: PYTHON-API-BACKEND
        build: .
        ports:
          - "8080:8080"
        volumes:
          - .:/opt/code/api
        depends_on:
          - db
    db:
        image: mysql:latest
        container_name: MYSQL-API-BACKEND
        env_file:
          - ./.env
        ports:
          - "3306:3306"
        volumes:
          - .:/opt/code/api/data 
