version: '3.8'

services:
    backend:
        container_name: PYTHON-API-BACKEND
        build: .
        ports:
          - "8000:8000"
        volumes:
          - .:/opt/code/api
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        depends_on:
          - db
    db:
        image: postgres:latest
        container_name: POSTGRES-API-BACKEND
        env_file:
          - ./.env
        ports:
          - "5432:5432"
        volumes:
          - .:/opt/code/api/data 
